name: Run Action

on: workflow_dispatch

jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: ./
        with:
          url: https://developer.chrome.com/

      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update screenshots
