name: Run Action

on: workflow_dispatch

jobs:
  run:
    name: Run
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: ./
        with:
          url: https://developer.chrome.com/